# AWS properties
aws:
  access-key: AKIA2LVXZB6L46BWYMAL
  secret-key: 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
  region: eu-north-1
  s3-bucket-name: pushkarawsbucket
  multipart-min-part-size: 5242880 # 5MB
